version: "3.8"

services:

  postgresql:
    container_name: database
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=posts
      - POSTGRES_USER=posts
      - POSTGRES_PASSWORD=posts-password

  stats_app:
    build: ./
    container_name: stats_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgresql
      - DB_NAME=posts
      - DB_USERNAME=posts
      - DB_PASSWORD=posts-password
    depends_on:
      - postgresql